ignoreWorkspaceRootCheck: true

minimumReleaseAge: 0
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*

allowBuilds:
  esbuild: true
  simple-git-hooks: true

overrides:
  semver: ^7.8.0
  vite: ^8.0.13
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
